AWS_ACCESS_KEY_ID = 'aws-access-key'
AWS_SECRET_ACCESS_KEY = 'aws-secret-key'
SECRET_KEY = 'test-secret-key'
SERVICE_NAME = 'zc-events-test'
BROKER_URL = 'amqp://guest:guest@rabbitmq:5672/%2F'
REDIS_URL = 'redis://redis:6379'
STAGING_NAME = 'test'
